[build-system]
requires = ['meson-python', 'nanobind', 'ruff', 'typing_extensions'] # nanobind is for stubgen
build-backend = 'mesonpy'

[project]
name = "pymmcore-nano"
requires-python = ">=3.10"
dynamic = ['version']
description = "CMMCore wrapper for Python, using nanobind"
readme = "README.md"
dependencies = ["numpy"]

[dependency-groups]
dev = [
    "ipython>=8.29.0",
    "meson-python>=0.17.1",
    "nanobind",
    "mypy>=1.13.0",
    "ninja>=1.11.1.2",
    "pdbpp>=0.10.3; sys_platform != 'win32'",
    "pre-commit>=4.0.1",
    "pytest",
    "ruff>=0.8.0",
]

# https://docs.pytest.org/
[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]
filterwarnings = ["error"]
