"""Protocols defining what the C++ bridge expects from Python device objects.

THESE ARE MANUALLY DEFINED.

These *should* mirror the methods that bridge_devices.h calls on Python device
objects via nanobind. Update these when bridge device classes change.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

    import numpy as np

    from . import DeviceCallbacks, PropertyHandle


class CreatePropertyFn(Protocol):
    """Callable passed to initialize() for registering MM properties."""

    def __call__(
        self,
        name: str,
        default_value: str,
        mm_type: int,
        read_only: bool,
        *,
        getter: Callable[[], str | int | float] | None = None,
        setter: Callable[[str], None] | None = None,
        pre_init: bool = False,
        limits: tuple[float, float] | None = None,
        allowed_values: Sequence[str] | None = None,
        sequence_max_length: int = 0,
        sequence_loader: Callable[[list[str]], None] | None = None,
        sequence_starter: Callable[[], None] | None = None,
        sequence_stopper: Callable[[], None] | None = None,
    ) -> PropertyHandle: ...


@runtime_checkable
class PyDevice(Protocol):
    """Base protocol for all Python bridge devices."""

    def initialize(
        self,
        create_property: CreatePropertyFn,
        notify: DeviceCallbacks,
    ) -> None: ...
    def shutdown(self) -> None: ...
    def busy(self) -> bool: ...


@runtime_checkable
class PyCamera(PyDevice, Protocol):
    """Protocol for Python camera devices."""

    def get_image_width(self) -> int: ...
    def get_image_height(self) -> int: ...
    def get_bytes_per_pixel(self) -> int: ...
    def get_number_of_components(self) -> int: ...
    def get_number_of_channels(self) -> int: ...
    def get_channel_name(self, channel: int) -> str: ...
    def get_bit_depth(self) -> int: ...
    def get_image_buffer_size(self) -> int: ...
    def get_exposure(self) -> float: ...
    def get_binning(self) -> int: ...
    def set_binning(self, bin: int) -> None: ...
    def set_roi(self, x: int, y: int, w: int, h: int) -> None: ...
    def clear_roi(self) -> None: ...
    def set_exposure(self, ms: float) -> None: ...
    def snap_image(self) -> None: ...
    def get_image_buffer(self, channel: int = 0) -> np.ndarray: ...
    def get_roi(self) -> tuple[int, int, int, int]: ...
    def is_exposure_sequenceable(self) -> bool: ...
    def is_capturing(self) -> bool: ...
    def start_sequence_acquisition(
        self,
        num_images: int,
        interval_ms: float,
        insert_image: Callable[[np.ndarray, dict | None], bool],
    ) -> None:
        """Start sequence acquisition.

        The device owns the acquisition loop — call `insert_image(array,
        metadata)` for each frame, synchronously or from a background thread.
        `insert_image` returns True on success, False when CMMCore's circular
        buffer is full. Stop acquiring when it returns False.
        """
        ...

    def stop_sequence_acquisition(self) -> None: ...


@runtime_checkable
class PyShutter(PyDevice, Protocol):
    """Protocol for Python shutter devices."""

    def get_open(self) -> bool: ...
    def set_open(self, open: bool) -> None: ...
    def fire(self, delta_t: float) -> None: ...


@runtime_checkable
class PyStage(PyDevice, Protocol):
    """Protocol for Python single-axis stage devices."""

    # position
    def set_position_um(self, pos: float) -> None: ...
    def get_position_um(self) -> float: ...
    def set_relative_position_um(self, d: float) -> None: ...
    def set_position_steps(self, steps: int) -> None: ...
    def get_position_steps(self) -> int: ...
    def set_adapter_origin_um(self, d: float) -> None: ...
    def set_origin(self) -> None: ...
    def get_limits(self) -> tuple[float, float]: ...
    # motion
    def move(self, velocity: float) -> None: ...
    def stop(self) -> None: ...
    def home(self) -> None: ...
    # focus
    def get_focus_direction(self) -> int: ...
    def is_continuous_focus_drive(self) -> bool: ...
    # sequencing
    def is_stage_sequenceable(self) -> bool: ...


@runtime_checkable
class PyXYStage(PyDevice, Protocol):
    """Protocol for Python XY stage devices."""

    # position (um)
    def set_position_um(self, x: float, y: float) -> None: ...
    def get_position_um(self) -> tuple[float, float]: ...
    def set_relative_position_um(self, dx: float, dy: float) -> None: ...
    def set_adapter_origin_um(self, x: float, y: float) -> None: ...
    # position (steps)
    def set_position_steps(self, x: int, y: int) -> None: ...
    def get_position_steps(self) -> tuple[int, int]: ...
    def set_relative_position_steps(self, x: int, y: int) -> None: ...
    # motion
    def home(self) -> None: ...
    def stop(self) -> None: ...
    def move(self, vx: float, vy: float) -> None: ...
    # origin
    def set_origin(self) -> None: ...
    def set_x_origin(self) -> None: ...
    def set_y_origin(self) -> None: ...
    # limits + step size
    def get_limits_um(self) -> tuple[float, float, float, float]: ...
    def get_step_limits(self) -> tuple[int, int, int, int]: ...
    def get_step_size_x_um(self) -> float: ...
    def get_step_size_y_um(self) -> float: ...
    # sequencing
    def is_xy_stage_sequenceable(self) -> bool: ...


@runtime_checkable
class PyState(PyDevice, Protocol):
    """Protocol for Python state devices (filter wheel, turret, etc.)."""

    def get_number_of_positions(self) -> int: ...


@runtime_checkable
class PyAutoFocus(PyDevice, Protocol):
    """Protocol for Python auto-focus devices."""

    def set_continuous_focusing(self, state: bool) -> None: ...
    def get_continuous_focusing(self) -> bool: ...
    def is_continuous_focus_locked(self) -> bool: ...
    def full_focus(self) -> None: ...
    def incremental_focus(self) -> None: ...
    def get_last_focus_score(self) -> float: ...
    def get_current_focus_score(self) -> float: ...
    def get_offset(self) -> float: ...
    def set_offset(self, offset: float) -> None: ...


@runtime_checkable
class PyGeneric(PyDevice, Protocol):
    """Protocol for Python generic devices (properties only)."""


@runtime_checkable
class PyHub(PyDevice, Protocol):
    """Protocol for Python hub devices."""

    def detect_installed_devices(self) -> Sequence[tuple[str, object, int]]:
        """Return peripherals as (name, py_device, device_type) tuples."""
        ...


@runtime_checkable
class PySLM(PyDevice, Protocol):
    """Protocol for Python SLM devices."""

    def set_image(self, pixels: np.ndarray) -> None: ...
    def display_image(self) -> None: ...
    def set_pixels_to(self, intensity: int) -> None: ...
    def set_pixels_to_rgb(self, r: int, g: int, b: int) -> None: ...
    def set_exposure(self, interval_ms: float) -> None: ...
    def get_exposure(self) -> float: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_number_of_components(self) -> int: ...
    def get_bytes_per_pixel(self) -> int: ...
