"""Protocols defining what the C++ bridge expects from Python device objects.

THESE ARE MANUALLY DEFINED.

These *should* mirror the methods that bridge_devices.h calls on Python device
objects via nanobind. Update these when bridge device classes change.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    import numpy as np

    from . import PropertyBridge


@runtime_checkable
class PyDevice(Protocol):
    """Base protocol for all Python bridge devices."""

    def initialize(self, bridge: PropertyBridge) -> None: ...
    def shutdown(self) -> None: ...
    def busy(self) -> bool: ...


@runtime_checkable
class PyCamera(PyDevice, Protocol):
    """Protocol for Python camera devices."""

    def get_image_width(self) -> int: ...
    def get_image_height(self) -> int: ...
    def get_bytes_per_pixel(self) -> int: ...
    def get_bit_depth(self) -> int: ...
    def get_image_buffer_size(self) -> int: ...
    def get_exposure(self) -> float: ...
    def get_binning(self) -> int: ...
    def set_binning(self, bin: int) -> None: ...
    def set_roi(self, x: int, y: int, w: int, h: int) -> None: ...
    def clear_roi(self) -> None: ...
    def set_exposure(self, ms: float) -> None: ...
    def snap_image(self) -> None: ...
    def get_image_buffer(self) -> np.ndarray: ...
    def get_roi(self) -> tuple[int, int, int, int]: ...
    def start_sequence_acquisition(
        self, num_images: int, interval_ms: float, stop_on_overflow: bool
    ) -> None: ...
    def stop_sequence_acquisition(self) -> None: ...


@runtime_checkable
class PyShutter(PyDevice, Protocol):
    """Protocol for Python shutter devices."""

    def get_open(self) -> bool: ...
    def set_open(self, open: bool) -> None: ...
    def fire(self, delta_t: float) -> None: ...
