name: CI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.platform }} (${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        platform: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: "14.2"

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.5"
          enable-cache: true

      - name: install and test
        shell: bash
        run: |
          # TODO: improve me...
          # this all got harder when trying to incorporate the C++ coverage
          # unclear whether we have to install in editable mode to get C coverage
          uv venv
          uv sync --frozen --no-install-project
          if [ ${{ runner.os }} == 'Windows' ]; then
            .venv\Scripts\activate
          else
            . .venv/bin/activate
          fi
          uv pip install -e . --no-build-isolation --force-reinstall \
            -C=setup-args="-Db_coverage=true" \
            -C=editable-verbose=true
          pytest --color=yes -v --cov --cov-report=xml
          gcovr --xml coverage_cpp.xml

      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml,./coverage_cpp.xml
